/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbyun_rtmp_NativeUtils */

#ifndef _Included_com_orbyun_rtmp_NativeUtils
#define _Included_com_orbyun_rtmp_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_orbyun_rtmp_NativeUtils
 * Method:    method
 * Signature: ()V
 */
JNIEXPORT void JNICALL_Java_com_orbyun_rtmp_NativeUtils_method
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
