/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbyun_player_PlayManager */

#ifndef _Included_com_orbyun_player_PlayManager
#define _Included_com_orbyun_player_PlayManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbyun_player_PlayManager
 * Method:    play
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_orbyun_player_PlayManager_play
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
